### ISSUE TITLE
[YAML] Disable schema validation if no schema matching the open file is registered

### ISSUE THREAD

**Issue by jonas-jonas** [eclipse/wildwebdeveloper#216]
In Dart projects a `pubspec.yaml` file is present containing project configuration.
Naturally it is opened in the YAML generic editor of WWD.

Upon first opening however there are syntax errors in the valid YAML file present (`Unexpected property environment` for example).
These are published by the language server. 
Oddly, they go away once the file was closed and then reopened.

Looks like WWD should tell the LS to not validate the file if there is no schema present?

**Comment by mickaelistria** [comment]
interesting. Can you please check how this works for VSCode? We're actually reusing the LS for VSCode so this could either be a bug in the LS, or a wrong configuration of the LS.

**Comment by jonas-jonas** [comment]
Works in VSCode for me. 

I was able to isolate this issue:
- Made a fresh install of Eclipse 2019-06
- installed only WWD
- created a `xx.yaml` file and pasted the following:
```
name: dsad
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Jonas Hungershausen <jonas.hungershausen@vogella.com>

environment:
  sdk: '>=2.4.0 <3.0.0' 
     
#dependencies:  
#  path: ^1.6.0   
  
dev_dependencies:
  build_runner: ^1.5.0
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0 
```

After looking around the codebase of WWD I noticed this: https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper/src/org/eclipse/wildwebdeveloper/yaml/YAMLLanguageServer.java#L55
Might be related, as it seems like the `validate` field is always set to true. Instead WWD should check if the file opened has a schema registered. 
Also the _Kubernetes_ schema is registered for all `.yaml` files? Shouldn't it only apply to kubernetes config files (though I'm not sure if they are identifiable?).
